sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "OWddQ86BHHYGF9TG+2rwM3sfjRfKt6BgwtiTh/cmAfWvyAzPU5z8NYGxe2Of7utX0iRkNnm3fadrKn+zmbuIfddhAfAlERgWfU30bjEML5hXFocxOGveiBg+dPaccrQWcToFcdttStRlKmI7KUpf7KWJ5bGidWvbWGLja63+oH4Hp3CZiyBMWOuLwRPzyggw+ND9+bNJfo8a4OebjIGu+mAL79M2l2npFNsi9eYOexAdHZlFpKb21z0mJ0rpscMjFRdZ1AThOJ5LZ2qKJ214WZU2UdinEcKRtS/rQbeKoq72Ru6sBJFsohFMSqoLavQjTgq0RS2v8lpdKff1Xqy2XkzyLOr4p29Y7Q6KOnm9V1lDFAnWcibVQ2KXRRzkmNkclAkMSDFzQ6M95h469Adfy2ZanVIwCnU11zcKWc6Zz2BzrkTAAFG+Fr0xGqRg6eQITycsaaBwpnxMgCRx38cEqyNwpWGdNtTi3wSILNCIk8uC8vbAFjhx2C6rgJOmZs7kfZEkkOtzzwoGPe1p/5BLNVF9Rhlqu+ZYwgJoc3xIcejB7EfxhjxuFTr/omoOC/kuj/qG08HLntOBhpFXfHDOLr61aGIloWVUGCpmtvSw1VFj847BdVLbR1yW+z5ri7kAGLM0gPbmp3J9zwz+hocKVhEk2U8pF7a39wLaCRrlzuY="
  - secure: "PkBp2iCoMuBKjf9HvX6DFpUnk0I9CASz/8LZeh3UMvPO27ieWS7ijUJ4w40oCmQ8jLMDaJEaC0XwodmTp9GMcL3Fr9085WVXi/gUXDi9Rp36GY/55hhkcvOGQP1lR771cOqNnVPM3do5U7kaMjaBi0XAvGLPnzHmXdt/ShxlLxLwI/Vyr5MZ0tVNWhlrzydC6vCtCAHGf3Xkfg/EGVJHCgq1WtKnmg1p/udRp2kvZrLKhyptPyyaP2BTEScsy30d7yALvEIZVwcy+1D/79lte3RuudCbJ27PJuhnhiZiXkShPhYviZ4rUvC8j33sMuTwMDZyp4nkMVOO0wj0B6f6CLXBkILj6adFM60D2lPuDwyrY9/QguYsCkWK43RI/d+Ey1JJUL81ycqM44xdz8MRn5EWYwIE2iqjAfngFWwMgZnSbuEM91GXsl9ldDK6GRdc0IYgn42lBV3FkkDY3vHM2rPgD6JjxWNKJ7OXXRuQJEBuOV7t8qVWmqw1kF/bdMKFBunZ/alufl5K7S56IIdplsGX7SbEc3MldLco7d8rTBLuOjSszjVL6qpWWwyNACHxbOTNiIak3TH6mpNcElmwwm4cuBV09RFzmsQ+c5aCWwOJy6M2loeQj0KUgzvXwd7RXJCLYUb/1CC6XSqwEEDHE5j6Ti6l8ygAm+8cJQr9kVc="
  - secure: "hQfEd07VbqtGF13MJhDJv+fBgklWmF6RdfM5wlOVC1Umy4UiDeUfMfaMQlV9a3V6SrRWV359kLFLjCY+j3gALxDYs+qgy5SyZu1LrBaDVLwTYBPOvypow7L5lKDU0w6CVvL5lbft9pmqzXfEL0GbmFtg/XyIZCecEq6IfbPww0GKhF310MsLrTswquXMLjo0WV4A3uabDlfvjubUF806ItBEriKkBbc11o8IHENc1UeO9C4skDCfQepDRZLiosO/uX/IHsrVr4xqLnNdrNIRnNqm4pqQqZQ3E7HgAweQmpE6IljKR3k+yF4q/yBNgHVQu/Oi+u12XW6r+vgezNN+ktTfcwT80JBNbCV3Bt+1RlhSHKtvTc6hD4gor2hmF66JOb6vn6dfBftYdX0oJ06y1xR8XsiQh73XIcTw4U4alPguc+w3oVgd5gBLi0VWOSFVCNmlySth3Wr+EP4hPo5jdHq4pvv6/ZwI0sEPeGq+n3yDz58HQwn4/14kLbswZqphT7DnKAJD3LhbKiI/eHn4/x/6aJ/UrgdSfxaDjkT/jkxIlNcoQ0henL67Nr1xuZ9xL8Nhrzp9dpBehbJW0HlKp6ecKbsnQhTK8nh8uHjyEz9v8/jsV/shlDSECwOZWR7QfGrvW45BxJZ1Es2v6e+RAhdi+LKc7CWiVEm33lcdQD0="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
